server:
  type: DefaultServer
  applicationConnectors:
  - type: http
    addr: localhost:8080
  adminConnectors:
  - type: http
    addr: localhost:8081
  requestLog:
    type: DefaultRequestLog
    appenders:
    - type: ConsoleAppender
    - type: FileAppender
      currentLogFilename: /tmp/melon-access.log

logging:
  level: DEBUG
  loggers:
    melon.server: INFO
    melon.configuration: WARN
  appenders:
  - type: FileAppender
    threshold: INFO
    currentLogFilename: /tmp/melon.log
  - type: ConsoleAppender

metrics:
  frequency: 1s
